-- local dbg = require("debugger")
-- dbg.auto_where = 2
local lst = require'tools.list'

local subject = {"one", "two", "three"}

describe("lst.partition", function()
  describe("an empty", function()
    local left, middle, right = lst.partition({}, 1, 2) 
    it("ignores indices", function()
      assert.are.same({}, left)
      assert.are.same({}, middle)
      assert.are.same({}, right)
    end)
  end)

  describe("general cases", function()
    describe("left bound", function()
      local left, middle, right = lst.partition(subject, 1, 2)
      it("lst.partitions", function()
        assert.are.same({}, left)
        assert.are.same({"one", "two"}, middle)
        assert.are.same({"three"}, right)
      end)
    end)
    describe("middle", function()
      local left, middle, right = lst.partition(subject, 2, 2)
      it("lst.partitions", function()
        assert.are.same({"one"}, left)
        assert.are.same({"two"}, middle)
        assert.are.same({"three"}, right)
      end)
    end)
    describe("right bound", function()
      local left, middle, right = lst.partition(subject, 2, 3)
      it("lst.partitions", function()
        assert.are.same({"one"}, left)
        assert.are.same({"two", "three"}, middle)
        assert.are.same({}, right)
      end)
    end)
    describe("into two", function()
      local left, middle, right = lst.partition(subject, 2, 1)
      it("lst.partitions", function()
        assert.are.same({"one"}, left)
        assert.are.same({}, middle)
        assert.are.same({"two", "three"}, right)
      end)
    end)
    describe("into one, LHS", function()
      local left, middle, right = lst.partition(subject, 4, 3)
      it("lst.partitions", function()
        assert.are.same(subject, left)
        assert.are.same({}, middle)
        assert.are.same({}, right)
      end)
    end)
    describe("into one, RHS", function()
      local left, middle, right = lst.partition(subject, 1, 0)
      it("lst.partitions", function()
        assert.are.same({}, left)
        assert.are.same({}, middle)
        assert.are.same(subject, right)
      end)
    end)
  end)

  describe("a regression", function()
      local left, middle, right = lst.partition(subject, 4, 1)
      it("lst.partitions", function()
        assert.are.same(subject, left)
        assert.are.same({}, middle)
        assert.are.same({}, right)
      end)
  end)

  describe("fault tolerance", function()
    local left, middle, right = lst.partition(subject, 4, 4)
    it("is ok", function()
      assert.are.same(subject, left)
      assert.are.same({}, middle)
      assert.are.same({}, right)
    end)
  end)
end)
