slice = require'tools.list'.slice
describe("empty", function()
  it("does nothing", function()
    slice({}, 1, 0, function()
      error("Never risen")
    end)
  end)
end)

describe("not empty", function()
  local table = {"a", "b", "c"}
  it("still may not do anything", function()
    slice(table, 2, 1, function()
      error("Never risen")
    end)
  end)
  describe("or just return a slice", function()
    it("does just this", function()
      assert.are.same({"b"}, slice(table, 2, 2))
    end)
  end)
  describe("or returned a mapped slice", function()
    it("still just does this", function()
      assert.are.same({"A", "B"}, slice(table, 1, 2, string.upper))
    end)
  end)
end)
