-- local dbg = require("debugger")
-- dbg.auto_where = 2
local slice = require'tools.list'.slice
local table = {"a", "b", "c"}

describe("empty", function()
  it("does nothing", function()
    slice({}, 1, 0, function()
      error("Never risen")
    end)
  end)
end)

describe("not empty", function()
  it("still may not do anything", function()
    slice(table, 2, 1, function()
      error("Never risen")
    end)
  end)
  describe("or just return a slice", function()
    it("does just this", function()
      assert.are.same({"b"}, slice(table, 2, 2))
    end)
  end)
  describe("or returned a mapped slice", function()
    it("still just does this", function()
      assert.are.same({"A", "B"}, slice(table, 1, 2, string.upper))
    end)
  end)
end)

describe("edge cases", function()
  it("can be off limits, LHS", function()
    assert.are.same({"a"}, slice(table, 0, 1))
  end)
  it("can be off limits, RHS", function()
    assert.are.same({"b", "c"}, slice(table, 2, 100))
  end)
  it("and become empty", function()
    assert.are.same({}, slice(table, 4, 1))
  end)
  it("and become empty, second index does not matter anymore", function()
    assert.are.same({}, slice(table, 4, 100))
  end)
end)
