name: CI
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: "5.2.0"
      - uses: leafo/gh-actions-luarocks@v4.0.0

      - name: build
        run: |
          luarocks install busted

      - name: test
        run: |
          (cd lua; busted -o utfTerminal spec)
