local lua = require('cccomplete.lua')()
describe("lua", function()

  describe("tail function spec", function()
    local function check_tail_fn_completion(name, input, fncompleted)
      local fncompleted = fncompleted or input
      local indent = string.match(input, "^%s*")
      local completion = lua.complete(input)
      describe(name, function()
        it("has the correct lines", function()
          assert.are.same({fncompleted, indent .. "  ", indent .. "end)"}, completion.lines)
        end)
        it("has the correct offset", function()
          assert.is_equal(1, completion.offset)
        end)
        it("has the correct col", function()
          assert.is_equal(999, completion.col)
        end)
      end)
    end

    check_tail_fn_completion("simple case", "something(function()")
    check_tail_fn_completion("commas too", "something(alpha, function()")
    check_tail_fn_completion("no parens, no problem", "something(function", "something(function()")
    check_tail_fn_completion("commas too, still no parens", "something(alpha, function", "something(alpha, function()")
    check_tail_fn_completion("shortcut", "  (fn", "  (function()")
    check_tail_fn_completion("with params", "  (alpha, function(a, b)")
  end)
end)
