local ruby = require'cccomplete.ruby'()
local function complete(line)
  return ruby.complete({line = line})
end
describe("ruby", function()

  describe("complete without do", function()
    describe("module", function()
      completion = complete("  module X")
      it("has the correct lines", function()
        assert.are.same({"  module X", "    ", "  end"}, completion.lines)
      end)
      it("has the correct offset", function()
        assert.is_equal(1, completion.offset)
      end)
      it("has the correct col", function()
        assert.is_equal(999, completion.col)
      end)
    end)

    describe("class", function()
      completion = complete("class Y")
      it("has the correct lines", function()
        assert.are.same({"class Y", "  ", "end"}, completion.lines)
      end)
      it("has the correct offset", function()
        assert.is_equal(1, completion.offset)
      end)
      it("has the correct col", function()
        assert.is_equal(999, completion.col)
      end)
      
    end)
  end)

  describe("complete with do", function()
    describe("any line", function()
      completion = complete("  something")
      it("adds a  do", function()
        assert.are.same({"  something do", "    ", "  end"}, completion.lines)
      end)
    end)
  end)
end)

